name: Autograding Tests

on:
  push:
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Bagian 1 Main Output Test
        id: test-p01mainoutputtest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bagian 1 Main Output Test
          command: mvn -q test -Dtest=P01MainOutputTest -DfailIfNoTests=true
          timeout: 10
          max-score: 5

      - name: Bagian 2 Author Test
        id: test-p02authortest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bagian 2 Author Test
          command: mvn -q test -Dtest=P02AuthorTest -DfailIfNoTests=true
          timeout: 10
          max-score: 5

      - name: Bagian 2 Book Test
        id: test-p02booktest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bagian 2 Book Test
          command: mvn -q test -Dtest=P02BookTest -DfailIfNoTests=true
          timeout: 10
          max-score: 10

      - name: Bagian 3 Encapsulation Test
        id: test-p03encapsulationtest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bagian 3 Encapsulation Test
          command: mvn -q test -Dtest=P03EncapsulationTest -DfailIfNoTests=true
          timeout: 10
          max-score: 10

      - name: Bagian 3 Member Test
        id: test-p03membertest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bagian 3 Member Test
          command: mvn -q test -Dtest=P03MemberTest -DfailIfNoTests=true
          timeout: 10
          max-score: 10

      - name: Bagian 4 Association Test
        id: test-p04associationtest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bagian 4 Association Test
          command: mvn -q test -Dtest=P04AssociationTest -DfailIfNoTests=true
          timeout: 10
          max-score: 5

      - name: Bagian 4 Shelf Aggregation Test
        id: test-p04shelfaggregationtest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bagian 4 Shelf Aggregation Test
          command: mvn -q test -Dtest=P04ShelfAggregationTest -DfailIfNoTests=true
          timeout: 10
          max-score: 10

      - name: Bagian 4 Composition Test
        id: test-p04membercardcompositiontest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bagian 4 Composition Test
          command: mvn -q test -Dtest=P04MemberCardCompositionTest -DfailIfNoTests=true
          timeout: 10
          max-score: 5

      - name: Bagian 4 Dependency Test
        id: test-p04librariandependencytest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bagian 4 Dependency Test
          command: mvn -q test -Dtest=P04LibrarianDependencyTest -DfailIfNoTests=true
          timeout: 10
          max-score: 5

      - name: Bagian 5 Inheritance Test
        id: test-p06inheritancetest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bagian 5 Inheritance Test
          command: mvn -q test -Dtest=P06InheritanceTest -DfailIfNoTests=true
          timeout: 10
          max-score: 10

      - name: Bagian 6 Overriding Test
        id: test-p07overridetest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bagian 6 Overriding Test
          command: mvn -q test -Dtest=P07OverrideTest -DfailIfNoTests=true
          timeout: 10
          max-score: 10

      - name: Bagian 6 Overloading Test
        id: test-p07overloadtest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bagian 6 Overloading Test
          command: mvn -q test -Dtest=P07OverloadTest -DfailIfNoTests=true
          timeout: 10
          max-score: 5

      - name: Bagian 7 Library Test
        id: test-p08librarytest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bagian 7 Library Test
          command: mvn -q test -Dtest=P08LibraryTest -DfailIfNoTests=true
          timeout: 10
          max-score: 5

      - name: Bagian 7 Console App Test
        id: test-p08libraryapptest
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bagian 7 Console App Test
          command: mvn -q test -Dtest=P08LibraryAppTest -DfailIfNoTests=true
          timeout: 10
          max-score: 5

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TEST-P01MAINOUTPUTTEST_RESULTS: "${{ steps.test-p01mainoutputtest.outputs.result }}"
          TEST-P02AUTHORTEST_RESULTS: "${{ steps.test-p02authortest.outputs.result }}"
          TEST-P02BOOKTEST_RESULTS: "${{ steps.test-p02booktest.outputs.result }}"
          TEST-P03ENCAPSULATIONTEST_RESULTS: "${{ steps.test-p03encapsulationtest.outputs.result }}"
          TEST-P03MEMBERTEST_RESULTS: "${{ steps.test-p03membertest.outputs.result }}"
          TEST-P04ASSOCIATIONTEST_RESULTS: "${{ steps.test-p04associationtest.outputs.result }}"
          TEST-P04SHELFAGGREGATIONTEST_RESULTS: "${{ steps.test-p04shelfaggregationtest.outputs.result }}"
          TEST-P04MEMBERCARDCOMPOSITIONTEST_RESULTS: "${{ steps.test-p04membercardcompositiontest.outputs.result }}"
          TEST-P04LIBRARIANDEPENDENCYTEST_RESULTS: "${{ steps.test-p04librariandependencytest.outputs.result }}"
          TEST-P06INHERITANCETEST_RESULTS: "${{ steps.test-p06inheritancetest.outputs.result }}"
          TEST-P07OVERRIDETEST_RESULTS: "${{ steps.test-p07overridetest.outputs.result }}"
          TEST-P07OVERLOADTEST_RESULTS: "${{ steps.test-p07overloadtest.outputs.result }}"
          TEST-P08LIBRARYTEST_RESULTS: "${{ steps.test-p08librarytest.outputs.result }}"
          TEST-P08LIBRARYAPPTEST_RESULTS: "${{ steps.test-p08libraryapptest.outputs.result }}"
        with:
          runners: test-p01mainoutputtest,test-p02authortest,test-p02booktest,test-p03encapsulationtest,test-p03membertest,test-p04associationtest,test-p04shelfaggregationtest,test-p04membercardcompositiontest,test-p04librariandependencytest,test-p06inheritancetest,test-p07overridetest,test-p07overloadtest,test-p08librarytest,test-p08libraryapptest
